image:
    file: .gitpod.Dockerfile

tasks:
  - command: |
      code helloworld.cot
      clear
      echo try:
      echo '  $ cotton helloworld.cot'
vscode:
  extensions:
    - nanikamado.cotton-language-server
